language: cpp
dist: trusty

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-7
        - g++-7
        - qt5-default
        - qt5-qmake
        
script:
    - qmake -v
    - ./configure && make && make test
    