language: cpp

matrix:
 include:
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=56

before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - sudo apt-get update -qq;
  - sudo apt-get install -y xvfb libquazip5-headers libquazip5-1 libquazip5-dev

install:
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi

script:
  - qmake -v
  - qmake -r
  - make

notifications:
  email: false
  
script:
    - cd tests
    - qmake
    - make
    - xvfb-run -a ./tests
    