language: cpp
dist: trusty

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-7
        - g++-7
        - qt5-default
        - qt5-qmake
env:
    - QT_VERSION=5.6.3

script:
    - qmake -v
    - qmake
    - make
    