language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get install qt5-default qt5-qmake xvfb

script:
    - cd tests
    - qmake tests.pro -spec linux-g++
    - make qmake_all
    - make
    - xvfb-run -a ./tests
    