language: cpp

matrix:
 include:
  - os: linux
    dist: xenial
    sudo: required
    compiler: g++
    env:
     - QT_BASE=56

before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-xenial -y; fi
  - sudo apt-get update -qq;
  - sudo apt-get install -y xvfb libquazip5-headers libquazip5-1 libquazip5-dev qt5-default qttools5-dev-tools qt5-qmake

install:
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi

notifications:
  email: false
  
script:
    - python -m SimpleHTTPServer 2443
    - cd tests
    - qmake tests.pro
    - make
    - xvfb-run -a ./tests
    