language: cpp
dist: trusty

matrix:
 include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=56

before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - sudo apt-get update -qq;

install:
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi

script:
  - qmake -v
  - qmake -r
  - make

notifications:
  email: false
  
script:
    - qmake -v
    - qmake -r
    - make
