language: cpp

matrix:
 include:
  - os: linux
    dist: xenial
    sudo: required
    compiler: g++
    env:
     - QT_BASE=56

before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-xenial -y; fi
  - sudo apt-get update -qq;
  - sudo apt-get install -y xvfb libquazip5-headers libquazip5-1 libquazip5-dev qt5-default qttools5-dev-tools qt5-qmake
  # Codecov
  - sudo pip install codecov
  
install:
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

notifications:
  email: false
  
script:
    - cd tests
    - python -m SimpleHTTPServer 2443 &
    - qmake tests.pro
    - make
    - xvfb-run -a ./tests
    # Codecov
    - tests/scripts/get_code_cov.sh

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
  