# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       bible

# >> macros
# << macros

Summary:    bible
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  bible.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   quazip
Requires:   sqlite
Requires:   qt5-qttest
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(sqlite3)
BuildRequires:  cmake >= 3.5
BuildRequires:  git
BuildRequires:  qt5-qttest
BuildRequires:  quazip-devel
BuildRequires:  sqlite-devel
BuildRequires:  desktop-file-utils

%description
Short description of my Sailfish OS Application


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr
make
# << build pre

%check
make test CTEST_OUTPUT_ON_FAILURE=TRUE

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
DESTDIR=%{buildroot} make install
mkdir -p %{_bindir}
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
/usr/include/sqlite_orm.h
/usr/lib/cmake/sqlite_orm/SqliteOrmConfig.cmake
/usr/lib/cmake/sqlite_orm/SqliteOrmConfigVersion.cmake
/usr/lib/cmake/sqlite_orm/SqliteOrmTargets.cmake
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/%{name}/translations/
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
