name: Github CI build

on:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]

env:
  RELEASE: 4.3.0.12
  SAILFISH_IMAGE: coderus/sailfishos-platform-sdk:$RELEASE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir -p ~/3rdparty

    - name: Pwd
      run: pwd
      
    - name: ls -la /home/runner/3rdparty
      run: ls -la /home/runner/3rdparty

    - name: Build aarch64
      run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            cd /share/3rdparty &&
            sudo mkdir test &&
            sudo touch test/.test.txt &&
            sudo touch test/test_.txt
            "

    - name: ls -la 3rdparty
      run: ls -la 3rdparty

    - name:  3rdparty /home/runner/3rdparty
      run: rsync -arvP --delete 3rdparty/ /home/runner/3rdparty

    - name: ls -la /home/runner/3rdparty/test
      run: ls -la /home/runner/3rdparty/test
      
    - name: Set up a cache for 3rdparty
      uses: actions/cache@v2
      with: 
        path: ~/3rdparty
        key: sailfish-3rdparty
        restore-keys: sailfish-3rdparty
