name: Github CI build

on:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]

env:
  RELEASE: 4.3.0.12

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir output

    - name: Cache 3rdparty
      id: cache-3rdparty
      uses: actions/cache@v2
      with:
        path: ~/3rdparty
        key: ${{ runner.os }}-3rdparty

    - name: Build aarch64
      run: docker run --rm --privileged $([ "$(ls -A ~/3rdparty)" ] && echo "-v ~/3rdparty:/share/3rdparty") -v $PWD:/share shevchenkoigor/docker-sailfishos-sdk:$RELEASE /bin/bash -c "
            cd /home/mersdk &&
            mkdir -p build &&
            cd build &&
            cp -r /share/* /share/.git* . &&
            #mb2 -t SailfishOS-$RELEASE-aarch64 build . &&
            ls -la 3rdparty/openssl/build && sudo cp -r RPMS/*.rpm /share/output"

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: output-rpms
        path: output

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in output/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
