name: Github CI build

on:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]

env:
  RELEASE: 4.3.0.12

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir output
      
    - name: Cache build
      id: cache-build
      uses: actions/cache@v2
      with:
        path: ~/build_/
        key: ${{ runner.os }}-build-
        restore-keys: ${{ runner.os }}-build-
        
    - name: ls -la ~/build_/
      run: ls -la ~/build_/

    - name: Build aarch64
      run: docker run --rm --privileged -v ~/build_:/home/mersdk/build_ -v $PWD:/home/mersdk/src coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            cd /home/mersdk/build_ &&
            sudo cp -fr /home/mersdk/src/.* /home/mersdk/build_/ && 
            sudo cp -fr /home/mersdk/src/* /home/mersdk/build_/ &&
            mb2 -t SailfishOS-$RELEASE-aarch64 build . &&
            sudo cp -r RPMS/*.rpm /share/output
            "

    - name: ls -la ~/build_/
      run: ls -la ~/build_/

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: output-rpms
        path: output

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in output/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
