name: Github CI build

on:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]

env:
  RELEASE: 4.3.0.12
  SAILFISH_IMAGE: coderus/sailfishos-platform-sdk:$RELEASE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p ~/image-cache

    - id: image-cache
      uses: actions/cache@v2
      with:
          path: ~/image-cache
          # Adjust key to meet your cache time requirements e.g.
          # ${{ hashFiles(*) }} can be useful here to invalidate
          # cache on file changes
          key: image-cache-${{ runner.os }}

    - name: Restore image
      run: docker image inspect $SAILFISH_IMAGE && docker load -i ~/image-cache/sailfishos.tar ||
            docker pull $SAILFISH_IMAGE && docker save -o ~/image-cache/sailfishos.tar $SAILFISH_IMAGE

    - name: Prepare
      run: mkdir output
      
    - name: Cache build
      id: cache-build
      uses: actions/cache@v2
      with:
        path: ~/build/
        key: ${{ runner.os }}-build-
        restore-keys: ${{ runner.os }}-build-
        
    - name: ls -la ~/build/
      run: ls -la ~/build/

    - name: Build aarch64
      run: docker run --rm --privileged -v ~/build:/build -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            mkdir src && cd src && 
            cp -fr /share/* /share/.git* . &&
            mb2 -t SailfishOS-$RELEASE-aarch64 build . &&
            ls -la &&
            sudo cp -fr * .mb* /build/ &&
            sudo cp -r RPMS/*.rpm /share/output
            "

    - name: ls -la ~/build/
      run: ls -la ~/build/

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: output-rpms
        path: output

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in output/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
