name: Code coverage Sailfish OS

on: [push]

env:
  RELEASE: 4.4.0.64
  ARCH: aarch64
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - uses: actions/checkout@v3

    - uses: act10ns/slack@v1
      with:
        status: starting
        channel: '#sailfish-os-code-coverage'
        message: Starting Build and Tests and Push code coverage
      if: always()

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_HUB_TOKEN }}

    - name: Build and Tests and Push code coverage
      run: >
        docker run --rm --privileged
        -e CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"
        -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        -e AWS_REGION=${{ secrets.AWS_REGION }}
        -e ARCH="${ARCH}"
        -v $PWD:/share ghcr.io/spiritecosse/bible-sailfishos-$ARCH:$RELEASE /bin/bash -c "
          curl https://raw.githubusercontent.com/spiritEcosse/aws-sailfish-sdk/master/install.sh | bash -s -- --func=code_coverage
        "

    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
           status: ${{ job.status }}
           steps: ${{ toJson(steps) }}
           channel: '#sailfish-os-code-coverage'
      if: always()
