name: Code coverage Sailfish OS

on: [push, pull_request]

env:
  RELEASE: 4.4.0.64
  SAILFISH_IMAGE: coderus/sailfishos-platform-sdk:$RELEASE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Tests
      run: >
        docker run --rm --privileged
        -e CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"
        -e IDENTITY_FILE="${{ secrets.IDENTITY_FILE }}"
        -e BACKUP_HOST="${{ secrets.BACKUP_HOST }}"
        -e BACKUP_USER="${{ secrets.BACKUP_USER }}"
        -v $PWD:/share coderus/sailfishos-platform-sdk-armv7hl:$RELEASE /bin/bash -c "
            alias mb2='mb2 --target SailfishOS-$RELEASE-armv7hl' &&
            export FILE=armv7hl.tar.gz &&
            export ID_FILE=/tmp/id &&
            cd /home/mersdk &&
            mkdir -p build &&
            cd build &&
            cp -fr /share/scripts/ . &&
            echo '================================ Download backup ===================================' &&
            cd ../ &&
            build/scripts/backup/download.sh &&
            cd build &&
            echo '================================ rsync -ar --stats --exclude '3rdparty' --exclude '.git/modules' /share/ . =============================' &&
            ls -la . &&
            sudo rsync -arv --stats --human-readable --exclude '3rdparty' --exclude '.git/modules' /share/ . &&
            sudo chown -R mersdk:mersdk . &&
            ls -la . &&
            mb2 build ;
            echo '================================ Upload backup =========================================' &&
            cd ../ &&
            build/scripts/backup/upload.sh ;
            cd build &&
            echo '================================ Run tests  =========================================' &&
            mb2 build-shell ctest --output-on-failure ;
            mkdir ccov &&
            echo '================================ make ccov-all-capture =================================' &&
            mb2 build-shell make ccov-all-capture &&
            echo '================================ Push results to codecov.io  ================================' &&
            curl -Os https://uploader.codecov.io/latest/linux/codecov &&
            chmod +x codecov &&
            ./codecov -t ${CODECOV_TOKEN} -f ccov/all-merged.info
            "
