name: Code coverage Sailfish OS

on: [push, pull_request]

env:
  RELEASE: 4.4.0.64
  SAILFISH_IMAGE: coderus/sailfishos-platform-sdk:$RELEASE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare Install lcov from tag v1.15
      run: sudo git clone https://github.com/linux-test-project/lcov.git && cd lcov && sudo git checkout tags/v1.15 && sudo make install

    - name: Tests
      run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk-armv7hl:$RELEASE /bin/bash -c "
            alias mb2='mb2 --target SailfishOS-$RELEASE-armv7hl' &&
            cd /home/mersdk &&
            mkdir -p build &&
            cd build &&
            cp -fr /share/* . &&
            cp -fr /share/.git* . &&
            mb2 test . &&
            sudo cp -r * /share/output
            "
            
    - name: Make lcov
      working-directory: /share/output
      run: |
        # Create lcov report
        # capture coverage info
        - lcov --directory . --capture --output-file coverage.info
        # filter out system and extra files.
        # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
        - lcov --remove coverage.info '*/usr/*' "${HOME}" '/.cache/*' '*/3rdparty/*' '*/tests/*' '*/lib/*' "*_autogen/*" --output-file coverage.info
        # output coverage data for debugging (optional)
        - lcov --list coverage.info

    - name: Upload coverage reports to Codecov
      working-directory: /share/output
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN} -X gcov
