name: Code coverage Sailfish OS

on: [push]

env:
  RELEASE: 4.4.0.64
  ARCH: armv7hl
  SAILFISH_IMAGE: coderus/sailfishos-platform-sdk:$RELEASE

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - uses: actions/checkout@v3

    - uses: act10ns/slack@v1
      with:
        status: starting
        channel: '#sailfish-os-code-coverage'
        message: Starting Build and Tests and Push code coverage
      if: always()
        
    - name: Build and Tests and Push code coverage
      run: >
        docker run --rm --privileged
        -e CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"
        -e IDENTITY_FILE="${{ secrets.IDENTITY_FILE }}"
        -e EC2_INSTANCE_USER="${{ secrets.EC2_INSTANCE_USER }}"
        -e EC2_INSTANCE="${{ secrets.EC2_INSTANCE }}"
        -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        -e AWS_REGION=${{ secrets.AWS_REGION }}
        -e AWS_REGION=${{ secrets.AWS_REGION }}
        -v $PWD:/share coderus/sailfishos-platform-sdk-$ARCH:$RELEASE /bin/bash -c "
            alias mb2='mb2 --target SailfishOS-$RELEASE-$ARCH' &&
            export ID_FILE=/tmp/id &&
            echo $ARCH &&
            echo "SailfishOS-$RELEASE-$ARCH" &&
            cd /home/mersdk &&
            mkdir -p build &&
            cd build &&
            cp -fr /share/scripts/ . &&
            cd ../ &&
            build/scripts/code_coverage.sh
            "

    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
           status: ${{ job.status }}
           steps: ${{ toJson(steps) }}
           channel: '#sailfish-os-code-coverage'
      if: always()
