name: cpp-linter

on:
    push:
        branches: []
    pull_request:
        branches: []
        
jobs:
    cpp-linter:
        name: cpp-linter
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: cpp-linter/cpp-linter-action@v2
            id: linter
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              style: file
